### PR TITLE
Fix expired authorization token error

### PR DESCRIPTION
**Pull request by lupugabriel1**
@hobailey I pushed a update to validate for 401 status code, and if so, renew the Authorization token and redo the request. Please let me know if there's any way I can simulate this behavior on the testing machines.
Thanks !

### CODE REVIEW

**Comment by lupugabriel1** [comment]
As a side mention, I will refactor this duplicated code if the solution is accepted. Thanks !

**Comment by hobailey** [comment]
Hey @lupugabriel1, thanks for the info. With this update, could the code not just get stuck in a loop though?
But more importantly, since the oauth tokens expire after 60mins, the SDK should store the expiry time and generate a new token without having to get a 401 before requesting a new token (like PHP for example: https://github.com/Mangopay/mangopay2-php-sdk/blob/master/MangoPay/Libraries/OAuthToken.php#L51)

**Comment by lupugabriel1** [comment]
That's a great point ! I was missing this aspect (that we can determine when the token will expire) ! Will update the PR with the implementation, thanks !

**Comment by lupugabriel1** [comment]
@hobailey I pushed a update that implements isExpired method to check if the token is still valid or not. Let me know if it's fine, thanks !

**Comment by hobailey** [comment]
Looks great, thanks very much :-)

**Comment by hobailey** [comment]
@lupugabriel1 we're still experiencing some problems with expired tokens being used - could you (if you haven't already) run some tests to check this is working correctly? Note that in sandbox, the tokens only last 20mins to help test this sort of thing :-)

**Comment by lupugabriel1** [comment]
@hobailey I will double-check this issue and make sure it's going to be stable. The 20m expiration date for the token will be very useful! Thanks!

**Comment by hobailey** [comment]
@lupugabriel1 any news with this?

**Comment by lupugabriel1** [comment]
@hobailey I have a PR on my queue that I did several extra-checks on! Will put it right away up!

**Comment by hobailey** [comment]
Great, thanks :-)

**Pull request merged**
