### PR TITLE
Preload models and services from predefined lists

### LINKED ISSUE #165: Error: ENOENT: no such file or directory, scandir '/services'
Trying to use this SDK but get an error. Not sure what other information you will find useful for debugging but happy to provide anything extra.

```
Error: ENOENT: no such file or directory, scandir '/services'
    at Object.readdirSync (fs.js:779:3)
    at Api._servicesLoader (/backend/services/stores/.webpack/service/webpack:/backend/node_modules/mangopay2-nodejs-sdk/lib/api.js:311:1)
    at new Api (/backend/services/stores/.webpack/service/webpack:/backend/node_modules/mangopay2-nodejs-sdk/lib/api.js:62:1)
    at create (/backend/services/stores/.webpack/service/webpack:/backend/services/stores/stores.js:143:21)
```

```
import mangopay from 'mangopay2-nodejs-sdk';

var mangoApi = new mangopay({
    clientId: '...',
    clientApiKey: '...',
    debugMode: true
});
```

Node: v12.3.1
 package.json: "mangopay2-nodejs-sdk": "^1.10.0",

### PR DESCRIPTION
**Pull request by jgautheron**
Instead of listing files under `models` and `services`, use deterministic lists.
One of the added advantages of doing that is to prevent i/o at runtime, and make the SDK compatible with bundlers such as Webpack.
Webpack is not only used for frontend environments but also backend, especially in serverless environments to have slim functions leveraging tree-shaking.

Fixes #165 #121 #140

### CODE REVIEW

**Comment by fredericdelordm** [comment]
Hello @jgautheron, 

First of all, thank you for your time and contribution. We are currently reviewing the pull request.

Have a nice day,

**Comment by fredericdelordm** [comment]
@jgautheron Thank you again for your time and contribution. Kudos for the quality of your work. We will provide soon a new release of the package. Have a nice day,

**Comment by SimoGh** [comment]
Hi @jgautheron, @fredericdelordm,
Any example showing how we can use the sdk with webpack?
I'm trying to use it in a cloudflare worker function.

Thanks,
Regards

**Comment by jgautheron** [comment]
Hi @SimoGh, any bundler will do (webpack, esbuild), I'd start with something like that: https://github.com/detroitenglish/cloudflare-workers-webpack-boilerplate

**Pull request merged**
