### PR TITLE
Add TypeScript support

### PR DESCRIPTION
**Pull request by ifiokjr**
## Usage

Without `"esModuleInterop": true` in tsconfig `compilerOptions`

```ts
import Mangopay = require("mangopay2-nodejs-sdk");
const api = new MangoPay(validConfig);
const payIn: MangoPay.models.PayIn = new api.models.PayIn({});
const address: MangoPay.models.Address = new api.models.Address({});

const addressData: MangoPay.Address.AddressData = {
  AddressLine1: '20 T Street',
  AddressLine2: '',
  City: 'London',
  Country: 'UK',
  PostalCode: 'FR43 2WE',
  Region: 'London',
};
```

Otherwise, when `"esModuleInterop": true` in tsconfig `compilerOptions`

```ts
import MangoPay, { models, Address } from 'mangopay2-nodejs-sdk';

const api = new MangoPay(validConfig);
const payIn: models.PayIn = new api.models.PayIn({});
const addressData: Address.AddressData = { ... };
```

## Trade-Offs

This library allows for both instantiated Models and plain objects to be passed as data parameters to API call. The model / plain model that is passed in is mutated with the successful response parameters.

To capture this behavior correctly with types was taking longer than I'd hoped so for now only plain objects should be used. You will also be expected to retrieve the data directly from the promise or callback.

The following will work.

```ts
import MangoPay from 'mangopay2-nodejs-sdk';

const validConfig: MangoPay.Config = {
  clientId: 'your_client_id',
  clientApiKey: 'your_client_api_key',
  baseUrl: 'https://api.mangopay.com',
};

const api = new MangoPay(validConfig);

api.Transfers.create({
  Fees: { Amount: 0, Currency: 'GBP' },
  AuthorId: 'user-id',
  DebitedFunds: { Amount: 2000, Currency: 'GBP' },
  DebitedWalletId: 'debit-wallet-id',
  CreditedWalletId: 'credit-wallet-id',
}).then(data => {
  console.log(data.ResultCode);
});
```

The following will not compile for typescript even though the underlying JS works.

```ts
const transfer = new api.models.Transfer({
  Fees: { Amount: 0, Currency: 'GBP' },
  AuthorId: 'user-id',
  DebitedFunds: { Amount: 2000, Currency: 'GBP' },
  DebitedWalletId: 'debit-wallet-id',
  CreditedWalletId: 'credit-wallet-id',
});

api.Transfers.create(transfer).then(data => {
  console.log(data.ResultCode);
});
```

The exception is for User objects where the instantiated model can be passed in as a parameter

```ts
// Use plain objects instead of models
const myUser = new api.models.UserLegal({
  Name: 'MangoPay',
  Email: 'info@mangopay.com',
  LegalPersonType: 'BUSINESS',
  LegalRepresentativeFirstName: 'Mango',
  LegalRepresentativeLastName: 'Pay',
  LegalRepresentativeEmail: 'mango@mangopay.com',
  HeadquartersAddress: new api.models.Address({
    AddressLine1: '4101 Reservoir Rd NW',
    AddressLine2: '',
    City: 'Washington',
    Region: 'District of Columbia',
    PostalCode: '20007',
    Country: 'US',
  }),
  LegalRepresentativeBirthday: 1300186358,
  LegalRepresentativeNationality: 'FR',
  LegalRepresentativeCountryOfResidence: 'FR',
  Tag: 'custom tag',
});

api.Users.create(myUser).then(function(data) {
  console.log(data.Name + ' user created at ' + data.CreationDate); // This is fine.

  // The following JS works, but TypeScript might complain. Don't rely on mutation.
  console.log(myUser.Name + ' user created at ' + myUser.CreationDate);
});
```

## Structure

The types have been placed into their own MangoPay namespace. This is a similar approach to the stripe-node library (see [types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/36a32d8a728c5d69685b115703b4d06c5c91b87d/types/stripe/index.d.ts#L38)) and has a similar disadvantage. TypeScript assumes a class declared in the namespace can be used as a value. This means the following which should not be allowed would compile correctly and fail at runtime.

<details><summary>View explanation</summary>
<p>

```ts
import MangoPay from 'mangopay2-nodejs-sdk';

const model = new MangoPay.models.Address({...}); // Fails  at runtime
```

The stripe type definition also has the same problem.

```ts
import Stripe from 'stripe';

const account = new Stripe.resources.Accounts(new Stripe('key'), {...}); // Fails at runtime
```

An alternative would have been to type each file individually e.g. `lib/models/Address.d.ts` and import each class into the top level type declaration. However, at this point, that would be a lot of work. It would probably be easier to do a rewrite of the library into TypeScript (which would be fantastic by the way!). 

</p>
</details>

<br>

## Tasks

This is a guideline of what would need to be done for 100% type coverage.

### Essential

- [x] Base types
- [x] Automate testing with dtslint

### Services

- [x] BankAccounts
- [x] BankingAliases
- [x] CardPreAuthorizations
- [x] CardRegistrations
- [x] Cards
- [x] Clients
- [x] DisputeDocuments
- [x] Disputes
- [x] Events
- [x] Hooks
- [x] KycDocuments
- [x] Mandates
- [x] PayIns
- [x] PayOuts
- [x] Refunds
- [x] Reports
- [x] Repudiations
- [x] Responses
- [x] Transfers
- [x] UboDeclarations
- [x] Users
- [x] Wallets

### Models

- [x] Address
- [x] BankAccount
- [x] BankAccountDetails
- [x] BankAccountDetailsCA
- [x] BankAccountDetailsGB
- [x] BankAccountDetailsIBAN
- [x] BankAccountDetailsOTHER
- [x] BankAccountDetailsUS
- [x] BankAccountType
- [x] BankingAlias
- [x] BankingAliasIBAN
- [x] Billing
- [x] Card
- [x] CardPreAuthorization
- [x] CardRegistration
- [x] Client
- [x] ClientWallet
- [ ] DebitedBankAccount
- [x] DeclaredUbo
- [x] DeclaredUboStatus
- [x] Dispute
- [x] DisputeDocument
- [x] DisputeDocumentPage
- [x] DisputeReason
- [x] Document
- [x] DocumentPageConsult
- [x] EMoney
- [x] EntityBase
- [x] Hook
- [x] KycDocument
- [x] KycDocumentStatus
- [x] KycDocumentType
- [x] KycPage
- [x] LegalPersonType
- [x] Mandate
- [x] MandateStatus
- [x] Money
- [x] PayIn
- [x] PayInExecutionDetails
- [x] PayInExecutionDetailsDirect
- [x] PayInExecutionDetailsWeb
- [x] PayInExecutionType
- [x] PayInPaymentDetails
- [x] PayInPaymentDetailsBankWire
- [ ] PayInPaymentDetailsBankingAlias
- [x] PayInPaymentDetailsCard
- [x] PayInPaymentDetailsCardDirect
- [x] PayInPaymentDetailsCardWeb
- [ ] PayInPaymentDetailsDirectDebitDirect
- [ ] PayInPaymentDetailsDirectDebitWeb
- [ ] PayInPaymentDetailsPayPal
- [x] PayInPaymentDetailsPreAuthorized
- [x] PayInPaymentType
- [x] PayInTemplateURLOptions
- [x] PayOut
- [x] PayOutPaymentDetails
- [x] PayOutPaymentDetailsBankWire
- [x] PayOutPaymentType
- [x] PersonType
- [x] PlatformCategorization
- [x] PlatformType
- [x] Refund
- [x] RefundReasonDetails
- [x] Report
- [x] ReportFilter
- [x] Repudiation
- [x] SecurityInfo
- [x] SettlementTransfer
- [ ] ShippingAddress
- [x] Transaction
- [x] Transfer
- [x] UboDeclaration
- [x] UboDeclarationRefusedReasonType
- [x] UboDeclarationStatus
- [x] UboRefusedReasonType
- [x] User
- [x] UserLegal
- [x] UserNatural
- [x] UserNaturalCapacity
- [x] Wallet

## Coverage

Coverage is quite extensive, however, due to a lack of my own usage I haven't found time to create types for the following:

```
✘ PayInPaymentDetailsBankingAlias
✘ PayInPaymentDetailsDirectDebitDirect
✘ PayInPaymentDetailsDirectDebitWeb
✘ PayInPaymentDetailsPayPal
✘ ShippingAddress
✘ DebitedBankAccount
```

They can be added trivially in the future so feel free to either edit this PR or merge and add at a later date.

### CODE REVIEW

**Comment by mickaelpois** [comment]
@ifiokjr Thanks for this very clear, clean and work you're doing on our Node SDK ! 🎉 ❤️ 
I'll have a closer look at it, can't wait to merge it and release it for all the community! 👍

**Comment by ifiokjr** [comment]
After some fixes to the code (including for some of the issues outlined in the initial post) I'm happy for this to be merged now.

@mickaelpois let me know if there's anything you'll need or any change requests.

**Comment by ifiokjr** [comment]
@mickaelpois have you had a chance to take a look?

**Comment by nemcek** [comment]
@ifiokjr I was using your types, which look great. However I think I found a mistake in the types. I believe here
https://github.com/Mangopay/mangopay2-nodejs-sdk/blob/7c81be838d3de7066532a70e2391edd19d0274c5/typings/index.d.ts#L1807
the `SecureModeRedirectUrl` should be `SecureModeReturnURL`. See [documentation for pre-authorization](https://docs.mangopay.com/endpoints/v2.01/preauthorizations#e184_create-a-preauthorization).

**Comment by ifiokjr** [comment]
@nemcek I've pushed up a fix

**Comment by kermiv** [comment]
@ifiokjr Looks like there is an inconsistency with Country field. In MangoPay api documentation, Country is in all cases referred to as "CountryIso", however in index.d.ts file it sometimes appears under this correct name "CountryISO" but sometimes, it is incorrectly referred to as "string"

For example:
```
    interface AddressData {
      AddressLine1: string;
      AddressLine2: string;
      City: string;
      Region: string;
      PostalCode: string;
      Country: string;
    }
```

With Currency there is no such a problem, it is always "CurrencyISO"

**Comment by iulian03** [comment]
Hi there @ifiokjr,

I updated your PR and brought it to the last version of the API. Also added missing types and fixed the 'CountryIso' inconsistency mention by @kermiv above.

It's ready to be merged, but something is not updating right in the 'Files Changed' section of this PR so i suggest closing it and making a new one instead, which i checked and it should work good.

**Comment by catacraciun** [comment]
We have solved the conflicts on another PR, I am declining this PR as it was merged in https://github.com/Mangopay/mangopay2-nodejs-sdk/pull/196 .

**Pull request closed without merging**
